### ISSUE TITLE
关于HDMI输出

### ISSUE THREAD

**Issue by andyy24** [zysuper/Thinkpad-X1-extreme-EFI#1]
这套EFI能用在10.13.X上吗? 如果可以的话安装WebDriver是不是就可以解决HDMI的问题

**Comment by zysuper** [comment]
理论上可行，你可以测试下

**Comment by andyy24** [comment]
再请问下你的配置是不是顶配4K的, 原装的PM981还能插着用吗, 另外无线网卡是不是换了?

**Comment by zysuper** [comment]
我是顶配4k。原装PM981我已经在ACPI里屏蔽了。请保证你的PM981插在nvem0，装mac的盘在nvem1口。然后，在mac下是完全看不到PM981的。无线网卡可以自行更换。因为这机器网卡使用了M.2 CNVio接口，很多兼容卡的蓝牙模块都无法识别。所以换了只能得到wifi得不到蓝牙。我是不能接受这种不完美的解决方案的。所以一直在用ASUS的USB AC53 nano + 外置原生蓝牙卡。

**Comment by andyy24** [comment]
您的意思是说常用的黑苹果网卡bcm94352z(DW1560A)和bcm943602(DW1830)替换以后蓝牙都不能用吗?

**Comment by andyy24** [comment]
Google了一下, M.2 CNVio是把USB通道给砍了导致老卡的蓝牙用不了了, 谢谢大神的回答!

**Comment by andyy24** [comment]
不好意思, 回头看了一下还有点问题. 外置原生蓝牙卡是指USB蓝牙适配器吗?
另外USB AC53 nano这个无线网卡是免驱的吗, 我在kexts文件夹里没有看到任何网卡的驱动

**Comment by zysuper** [comment]
USB AC53 nano可以用realtek无线网卡通用mac驱动。我可以上传一个。外置原生蓝牙卡是指USB蓝牙适配器可以在淘宝买到。就是设备体积有点大，好处是原生，无需驱动。

**Comment by andyy24** [comment]
谢谢你的耐心回答.

**Comment by zysuper** [comment]
官方的驱动会掉线。请用我github上的驱动。intel的蓝牙也可以驱动，你可以先进一次windows，再回mac就能驱动了。但是，我的efi默认屏蔽intel蓝牙。

andyy24 <notifications@github.com> 于2018年11月19日周一 下午3:05写道：
