### ISSUE TITLE
ThinkPad P1黑苹果求助

### ISSUE THREAD

**Issue by wellrex** [zysuper/Thinkpad-X1-extreme-EFI#10]
你好，我最近购入一台ThinkPad P1，配置为i7 8750H，8+16G内存，Intel 256G+WD 500G SSD，4K UDH。
我使用了FakeSMC.kext，Lilu.kext，USBInjectAll.kext，VoodooPS2Controller.kext，WhateverGreen.kext，VoodooHDA 成功安装了Mojave 10.14 。
显卡，声卡工作正常，但是休眠，电池电量显示无法正常工作，搜索了网上发现没有任何P1黑苹果的信息。
然后我寻找兄弟机型X1E的黑苹果相关信息，发现全网只有你解决了休眠和电量问题。
两台机子的驱动和BIOS都是通用的，所以我使用了你的ssdt和dsdt。单独使用ssdt可以正常进入系统，而且屏蔽独显也起了作用，但是如果使用了dsdt，系统就会卡在启动过程中，显示ACPI: Executed 44 blocks of module-level executable AML code。
由于本人能力有限，无法修正dsdt的问题，希望在您这里能够得到帮助。
[origin.zip](https://github.com/zysuper/Thinkpad-X1-extreme-EFI/files/2753864/origin.zip)

**Comment by wellrex** [comment]
自己瞎搞了一会儿,休眠似乎正常了,但是电池电量的问题还是搞不定,请高手出手相助

**Comment by wellrex** [comment]
对比了差异，终于搞定了dsdt，非常感谢 @zysuper 的贡献

**Comment by zysuper** [comment]
Congratulations! 🎉🎉🎉

**Comment by wellrex** [comment]
还有一个问题就是显示的电量要比实际电量高4%，比如实际电量是76%，显示的是80%。然而用HWSensors看到的电量信息是正确的。@zysuper
