### ISSUE TITLE
提供一点小小的改进，修正小红点漂移

### ISSUE THREAD

**Issue by andyy24** [zysuper/Thinkpad-X1-extreme-EFI#11]
ssdt文件修改来源于 https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller，可以修正小红点移动过快，漂移的问题。直接开个问题，不pull了。

[ssdt-clickpad.zip](https://github.com/zysuper/Thinkpad-X1-extreme-EFI/files/2775370/ssdt-clickpad.zip)

**Comment by zysuper** [comment]
nice! Thank you!
