### ISSUE TITLE
Unsmoot typo in Thinkpad_Clickpad.dsl

### ISSUE THREAD

**Issue by gfoury** [zysuper/Thinkpad-X1-extreme-EFI#12]
https://github.com/zysuper/Thinkpad-X1-extreme-EFI/blob/112fcb177cbad236176062705fc302a72d222a40/ACPI/dsl-patch/SSDT-Thinkpad_Clickpad.dsl#L35

This says `UnsmootInput`; should it say `UnsmoothInput`?

**Comment by gfoury** [comment]
I filed https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/pull/181.

**Comment by zysuper** [comment]
Thank you! Fixed it.
