### ISSUE TITLE
升级到10.14.4以后出现睡眠后无声

### ISSUE THREAD

**Issue by andyy24** [zysuper/Thinkpad-X1-extreme-EFI#13]
升级到10.14.4以后出现睡眠后无声，请问有没有解决方法？疑似CodeCommander.kext失效了。

**Comment by zysuper** [comment]
ALCPlugFix守候进程你装了吗？

**Comment by andyy24** [comment]
> ALCPlugFix守候进程你装了吗？

没有，能提供一个吗？那个怎么修改的图挂了

**Comment by zysuper** [comment]
源里面有啊。
有编译好的。
https://github.com/zysuper/Thinkpad-X1-extreme-EFI/tree/master/ALCPlugFix/alc_fix

**Comment by andyy24** [comment]
> 源里面有啊

我瞎了，我只看了说明，一心以为要自己编译一个。。。

**Comment by andyy24** [comment]
安装以后，休眠依然无声。
临时解决方案：开启一次睡眠，不等进入睡眠状态，显示器黑屏后按键盘任意键中断睡眠，进入桌面后声音恢复正常。

**Comment by andyy24** [comment]
请问applealc你做了什么修改，为什么我直接用https://github.com/acidanthera/AppleALC的release版本无法识别声卡？

**Comment by andyy24** [comment]
问题解决了，更新了最新的applealc，注入id 11就正常了，无需ALCPlugFix，休眠耳机一切正常。
