### ISSUE TITLE
the cursor jumping when typing words

### ISSUE THREAD

**Issue by wdde** [zysuper/Thinkpad-X1-extreme-EFI#14]
Hi zysuper, I am using your efi file and running the hackintosh, thanks for your work, I found the cursor would move to another location when I typing words，any suggestion?

**Comment by zysuper** [comment]
Did you confirm that you didn't touch the trackpad when typing?

**Comment by wdde** [comment]
yes, I did, absolutely no touch

**Comment by wu-hongjun** [comment]
I don’t remember if zysuper used VoodooPS2Controller.kext, but you should experiment with different VoodooPS2Controller if you haven’t done so.

**Comment by wdde** [comment]
Thinks, I'll try it later.

**Comment by wdde** [comment]
> I don’t remember if zysuper used VoodooPS2Controller.kext, but you should experiment with different VoodooPS2Controller if you haven’t done so.

我看了下，zysuper给出的kext/other中已经有了，所以你说的使用“不同的VoodooPS2Controller.kext”是什么 ？是不是有针对性修改的VoodooPS2Controller.kext？

The EFI given by zysuper is already has a VoodooPS2Controller.kext, so what do you mean by using "different VoodooPS2Controller.kext"? Is there a thirdparty modification of VoodooPS2Controller.kext?

**Comment by wdde** [comment]
已经证实是多手势的voodoops2 kext导致

**Comment by zysuper** [comment]
voodoops2 driver issue. closed.
