### ISSUE TITLE
ALCPlugFix guide picture link is missing , plz check it.

### ISSUE THREAD

**Issue by wdde** [zysuper/Thinkpad-X1-extreme-EFI#15]
The link direct to ALCPlugFix_ALC256 is missing:

“ 打开ALCPlugFix目录下面的main.m,将包含hda-verb语句的几行修改成如图所示ALCPlugFix_ALC256”

**Comment by zysuper** [comment]
有编译好的，不需要看这个说明啊，亲。

**Comment by wdde** [comment]
谢谢，我回头试试。
