### ISSUE TITLE
Patching ACPI

### ISSUE THREAD

**Issue by erv5** [zysuper/Thinkpad-X1-extreme-EFI#18]
Hey zysuper first off I want to say Thank You for all the work you've done regarding the X1 Extreme Hackintosh and even finding a taobao seller that sells a perfect adapter + card for this model!

But do you mind helping me out with patching my DSDT file and applying the other patches? I am having issues with:
**1. Audio working randomly
2. Brightness Keys (Brightness in settings work)
3. Graphics glitch a bit when booting into macOS from Clover
4. Pressing my mute button only displays it is muting the sound not unmuting though the light on the mute key does turn on/off as I press the mute key.** 

If you could write a short tutorial for what to do that would help greatly as I prefer to learn and it could help others.I've been reading and getting more confused. Some Questions:
**1. What is the apfs patch used for? (Only macOS Serria?) 
2. What about the ALCPlugFix, I'm not having any issues regarding with the headphone jack that I know of as I don't use it. 
3. What about the patches like SSDT_DDGPU.aml .etc do I just throw them into the ACPI/Patched folder or is there some extra patching of some sort required?
4. Do I also just throw the kext into the kext/other folder or do I have to do something else with them like using a kext installer?**

If anyone can contribute please assist and thanks in advance. This is my 2nd Hackintosh but I never actually correctly set up the first one.
[EFI.zip](https://github.com/zysuper/Thinkpad-X1-extreme-EFI/files/3293658/EFI.zip)
[DSDT.aml.zip](https://github.com/zysuper/Thinkpad-X1-extreme-EFI/files/3293659/DSDT.aml.zip)

**Comment by zysuper** [comment]
Issues: 
1. Starting from 10.14.4, the frequency of not finding a sound card at startup is getting higher.
2. You need to patch _Q14, _Q15 Method in your dsdt.aml. 
    _Q14:  append `Notify (KBD, 0x0406)`
    _Q15:  add `Notify (KBD, 0x0405)` before `Return (Zero)`
![image](https://user-images.githubusercontent.com/5764723/59593801-30cbf080-9125-11e9-959b-1409915d1a8d.png)

3. Just a little bit.
4. Yes, it is.

Questions:
1. If you don't want to use ApfsDriverLoader.efi, you can use this patched apfs.efi directly, it won't print a bunch when booting.
2. if you not having any issues, don't use ALCPlugFix.
3. SSDT_DDGPU.aml use for disable dedicated gpu, just for power save maybe.
4. Kext can be placed in kext/other.

**Comment by gfoury** [comment]
If you don't patch `_Q14` and `_Q15`, you still may have brightness keys, just hidden on `Fn-P` (brightness up) and `Fn-K` (brightness down).

@zysuper, thanks for documenting what needs to be done for `_Q14` and `_Q15`. It would be nice to be able to handle them with hot-patching, but there isn't an obvious place to insert the extra call.

I wonder if `\VIGD` is true when discrete graphics are turned on. If that is the case, then we can overwrite the `If` statement to just be `Notify(); Notify();`.

**Comment by zysuper** [comment]
Hot patching is possible, you can use the config file to rename the mate, even the battery patch can be hot patched. I am lazy.

**Comment by erv5** [comment]
Wow, thank you so much Zysuper you have been a great help. I am going to try these fixes tonight and give an update on what happens. I did notice the small changed you did to Q14 Q15 initially when searching your DSDT file but wasn't sure if you applied some sort of patch because our line numbers didn't match.

But before I get started I had a few more questions:

1. **Which SSDT files are needed when patching the DSDT.aml file?** 
I have been running into issues using "iasl -da -dl -fe refs.txt DSDT.aml SSDT*.aml"

**Comment by zysuper** [comment]
iasl -dl DSDT.aml SSDT*.aml

**Comment by erv5** [comment]
<img width="626" alt="Screen Shot 2019-06-18 at 2 40 34 AM" src="https://user-images.githubusercontent.com/51408546/59810635-429fc600-92d4-11e9-8c71-6fd99e0b5382.png">
Should I be using all these SSDT files?

**Comment by zysuper** [comment]
Yes, you can.

**Comment by erv5** [comment]
I got it my DSDT file patched thanks! I really appreciate all the support and quick responses.

Last thing, for now, how do I apply that APFS patch? I've been using this file and it also gets rid of the text but I don't know if it breaks another function.
[ApfsDriverLoader-64.efi.zip](https://github.com/zysuper/Thinkpad-X1-extreme-EFI/files/3308402/ApfsDriverLoader-64.efi.zip)

**Comment by zysuper** [comment]
The apfsDriverLoader.efi and apfs.efi functions are the same.

**Comment by gfoury** [comment]
@zysuper I forgot [what I had done on the ASUS UX305FA](https://github.com/gfoury/UX305FA-DSDT-Patch/blob/master/SSDT-BATT.dsl). If you're willing to duplicate code into an SSDT, yeah, it's not so bad to hotpatch. Maybe I will work on this for the X1E.

**Comment by ergonyc** [comment]
@hermes137 what BIOS version are you using?  I accidentally updated the BIOS to 1.21 and haven't been able to get a reboot yet.  Can you confirm which one you are using?

**Comment by ergonyc** [comment]
Also,  can anyone offer advice on navigating Taobao for a non-chinese speaker to get the adapter with USB extension to enable bluetooth?
