### ISSUE TITLE
BIOS 1.21 - Stuck after End RandomSeed with ++++++++++++

### ISSUE THREAD

**Issue by snoerenberg** [zysuper/Thinkpad-X1-extreme-EFI#20]
Hi,
currently the start of the mojave installer is stuck with "End RandomSeed"

I tried to remove the DSDT.aml but it won't boot either.
It has 64GB RAM - not sure if this could cause a problem.

[origin_FW_1.21.zip](https://github.com/zysuper/Thinkpad-X1-extreme-EFI/files/3336443/origin_FW_1.21.zip)

![IMG_9090](https://user-images.githubusercontent.com/4847454/60297326-3943d880-9928-11e9-8bae-a75fcd8353cc.jpg)

I tried both USB ports but makes no difference. Any other ideas?

Thanks a lot

**Comment by snoerenberg** [comment]
Even with only one 32GB module it's the same. In DIMM1 (not DIMM2).

**Comment by snoerenberg** [comment]
Trying DIMM2 helped not to be stuck at End RandomSeed

**Comment by andrewwiik** [comment]
So the RAM is the issue on this, you can't use 64GB of RAM?

**Comment by snoerenberg** [comment]
I could use 64 GB after I installed with 32GB, I installed Clover to the local SSD and with the clover configurator I used the following settings found here:

https://www.insanelymac.com/forum/topic/338273-mojave-10144-installs-with-1x32gb-module-hangs-end-randomseed-with-2x32gb/?do=findComment&comment=2670184

![grafik](https://user-images.githubusercontent.com/4847454/60400930-e1e97680-9b7a-11e9-8713-46da7fbdbe89.png)

Even if I have only 2x32GB

**Comment by andrewwiik** [comment]
Did you use two 16GB sticks or? Because when I only have 1 32GB stick
installed my computer won’t even turn on to get the boot menu to select the
USB

**Comment by andrewwiik** [comment]
Could you send your clover config minus the serial you’re using obviously.

**Comment by snoerenberg** [comment]
@andrewwiik 
[config_64GB.zip](https://github.com/zysuper/Thinkpad-X1-extreme-EFI/files/3343282/config_64GB.zip)

**Comment by andrewwiik** [comment]
Can I get the entire EFI folder so I have aptiomemoryfix you used as well @snoerenberg

**Comment by snoerenberg** [comment]
At the end it was this (w/o the RAM patch in the config.plist)
[EFI_32GB_Install.zip](https://github.com/zysuper/Thinkpad-X1-extreme-EFI/files/3343289/EFI_32GB_Install.zip)

its from this repo: https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme

**Comment by andrewwiik** [comment]
I got the installer booted finally, thank you so much, do you plan on doing the custom WiFi solution they suggested here?

**Comment by andrewwiik** [comment]
I noticed graphics acceleration isn’t working, is this known? (I know it
can’t use the dedicated GPU)

**Comment by snoerenberg** [comment]
Hi, GPU and WiFi I have not investigated yet.

**Comment by andrewwiik** [comment]
@snoerenberg So your graphics acceleration doesn't work either?
