### ISSUE TITLE
Some information : two method to enable multitouch touchscreen

### ISSUE THREAD

**Issue by Jamesxxx1997** [zysuper/Thinkpad-X1-extreme-EFI#22]
Hi , I'm a user from thinkpad x1 yoga 2018
This laptop has a usb-hid touchscreen , I guess the 4K version of x1 extreme should be same(look up about this Mac > system report > USB , can find out the "pen and multitouch sensor" , and you can see the vendor id ; product id of it)
![image](https://user-images.githubusercontent.com/29252582/61428223-ca203980-a953-11e9-8dd9-bb8440c9199c.png)

The first way to enable multitouch is adding [voodooi2c , voodooi2chid](https://github.com/alexandred/VoodooI2C) into \library\extension 

The second way is buying touch driver from [touch-base](https://touch-base.com) , the driver cost about 95 USD , you can try it for free by contacting them.
I have record some video about it : https://www.youtube.com/channel/UCmVLJUv2nHImPS5CbaUuyKQ

Hope these informations helps :)

噢，還有一件事情
請問可以加您的QQ嗎？ 我想知道一下x1 extreme觸屏的情況(有些bug我不確定是否在每個觸屏上都會發生) 感謝🙏

**Comment by wdde** [comment]
Great work!  thanks so much @Jamesxxx1997

**Comment by zysuper** [comment]
Great work! thanks so much @Jamesxxx1997
