### ISSUE TITLE
请问如何从Linux中得到“pinData”并注入profile 7？

### ISSUE THREAD

**Issue by xuzhao9** [zysuper/Thinkpad-X1-extreme-EFI#23]
出现一些声卡问题，可能因为我的声卡和您的不一样。
不知道可否提供一下详细的AppleALC.kext定制过程？我有一块Linux USB盘，希望可以得到pinDATA相关信息，我的声卡也是Realtek ALC285。

**Comment by zysuper** [comment]
定制过程可以看看 黑果小兵的 网站。
