### ISSUE TITLE
请问替换网卡为943602cs之后插电源自动开机的问题是如何解决的？

### ISSUE THREAD

**Issue by Calciferx** [zysuper/Thinkpad-X1-extreme-EFI#25]
RT

**Comment by zysuper** [comment]
解决不了。我现在都在用 intel 网卡了。 蓝牙已经被后浪们解决了。wifi 支持后浪们还在开发中。

**Comment by Calciferx** [comment]
> 解决不了。我现在都在用 intel 网卡了。 蓝牙已经被后浪们解决了。wifi 支持后浪们还在开发中。

解决了，使用联想电脑管家或者Vantage将 USB持续供电  设置为 从关机开始充电  就可以了

**Comment by zysuper** [comment]
Nice Job.

**Comment by Calciferx** [comment]
完美解决方案：
从没有缺口的方向数，使用透明胶带屏蔽转接卡正面第 11，12 引脚，背面第 3，4，5 引脚。
（猜测）更换94360CS2后进入WIN10冻屏卡死的问题也许可以采取相同的处理措施。
