### ISSUE TITLE
Battery SSDT + NVMeFix

### ISSUE THREAD

**Issue by averycblack** [zysuper/Thinkpad-X1-extreme-EFI#26]
I posted an issue over on Errrniest's repo, but I think this repo would benefit as well.

I've seperated the battery changes and Brightness keys out of the DSDT into seperate SSDTs. This means if you do a BIOS update, you don't need to update your DSDT if it gets updated during the update. It also allows you to track the changes much easier. This does require renames in the config.plist as well.

NVMeFIX is recommended for all laptops too, and is from Acidanthera. It fixes power management on NVMe SSDs and I think contributes to the reat battery life I've had with my laptop, especially in sleep (I lose only < 2% every 3-5 hours of battery)

It is an opencore config, but the ACPI patches should be copy and paste for the most part. Might want to take a look at Device Properties too (should be copy and paste as well, no different from Clover)

I may put in a pull request either into this repo or Errrniest's repo, I'm not sure yet.

My repo: https://github.com/1Revenger1/X1-Extreme-OpenCore-Resources

**Comment by zysuper** [comment]
Thank you for your contribution. I started from the day before yesterday, and also turned to OpenCore.

**Comment by averycblack** [comment]
No problem. You may look into VoodooRMI too - it's pretty stable at this point. It handles 3 and 4 finger gestures much better as it can get the data for all fingers. Doesn't require any acpi edits as well
