### ISSUE TITLE
I am using a smart card bought from tabao but now I can't enable bluetooth on macOS :((

### ISSUE THREAD

**Issue by pyisme** [zysuper/Thinkpad-X1-extreme-EFI#27]

**Comment by zysuper** [comment]
Check your usbinjectall.kext is worked, maybe you must check your config.plist . Make sure boot flags add `uia_exclude=HS14,HS05,HS06,USR1,USR2`. (HS14 is builtin bluetooth must be disabled.)

**Comment by wdde** [comment]
What is your mean “builtin” ? If I insert the intel 9560ngw ,  it will occupy the hs14 USB port?  If I using the apple combo 2in1 card, the Bluetooth just connect to hs11?  I found a funny thing I cannot power on if the 9560ngw inserted

**Comment by zysuper** [comment]
macos only allows one Bluetooth device. intel card bluetooth use hs14.
