### ISSUE TITLE
UEFI boot item issue

### ISSUE THREAD

**Issue by garylee129** [zysuper/Thinkpad-X1-extreme-EFI#29]
I find that an UEFI boot item named "Opencore" will be automatically created, even if I delete this, it will be created again after logging into the system, I wonder if it can be cancelled?

**Comment by zysuper** [comment]
good question. that's opencore protect uefi boot flag turn on.
I will tell you the specific modification items under test.

garylee129 <notifications@github.com> 于 2020年7月15日周三 上午12:47写道：

**Comment by zysuper** [comment]
<img width="906" alt="image" src="https://user-images.githubusercontent.com/5764723/87495388-dda7d280-c683-11ea-8b74-a726c6842a3c.png">

**Comment by garylee129** [comment]
thanks for your reply, I changed the values and it works.
