### ISSUE TITLE
Compatibility Issues

### ISSUE THREAD

**Issue by wu-hongjun** [zysuper/Thinkpad-X1-extreme-EFI#3]
So I worked based on your work, and came up with an own solution of mine.
It is currently posted at https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/releases/tag/v10.14.0.1

First, I'd like to thank you for your work, as it contributed hugely to my project.
And there are several things I discovered that might be useful for people.

1. I tried to make SMBIOS with MacBook 15,1 work, but it suffers from poor compatibilities, so you are correct on setting SMBIOS to 15,2.
2. While using the SSDT patches, there are two SSDTs that doesn't work on my machine. One is the SSDT_NVMe-Pcc.aml, which leads to a kernel panic. Another is SSDT-DDGPU.aml, which leads to a reboot after ten seconds the system is logged in. I am curious how you bypass these problems.
3. AppleALC isn't working properly on my machine. It is not a big deal since I solved it using VoodooHDA.kext, but I am really interested to know how you attempted to solve AppleALC.kext.
4. In your readme.MD you said that the reason for not having NVIDIA card working is because there isn't appropriate web driver, but I think since the dGPU implements the NVIDIA Optimus technology which is not supported by macOS, dGPU is unlikely to work no matter what.

Again, thanks and I hope these also help other people!

**Comment by zysuper** [comment]
1.SSDT_NVMe-Pcc.aml is used to disable PM981 in the main hard disk interface, because PM981 can not be used to install mac.
2.SSDT-DDGPU.aml is used to disable the discrete graphics card, he will not bring any problems.
3. You may have to uninstall VoodooHDA.kext first and inject layout id in clover. The AppleALC.kext solution is more natively supported by the macos system than the VoodooHDA generic solution.
4. You can not recognize the discrete graphics card at all, he can be identified by macos, because the direct display is directly output to hdmi. In this regard, you can go to windows to see which graphics card your external monitor is connected to.

**Comment by wu-hongjun** [comment]
It seems like all external ports are connected to the dGPU.

**Comment by zysuper** [comment]
Yes,You are right,Like Desktop PC,You can connect external display to dGPU
or iGPU.

Hongjun Wu <notifications@github.com> 于2018年11月19日周一 下午3:54写道：

**Comment by fylimas** [comment]
Hi, guys!

So does the dGPU implement the NVIDIA Optimus technology? That is, is there any  hope for driving the NVIDIA card?🤔️

In Chinese:
所以说，这个英伟达显卡是Optimus技术吗？也就是说显卡是不是无望了。如果不是Optimus技术，那么用High Sierra还是可以的，因为有web driver

**Comment by wu-hongjun** [comment]
> Hi, guys!
> 
> So does the dGPU implement the NVIDIA Optimus technology? That is, is there any hope for driving the NVIDIA card?🤔️
> 
> In Chinese:
> 所以说，这个英伟达显卡是Optimus技术吗？也就是说显卡是不是无望了。如果不是Optimus技术，那么用High Sierra还是可以的，因为有web driver

I am pretty sure it is Optimus. If not, iGPU will be completely disabled (which you can do in BIOS) so it is not completely hopeless. However I have not test that option on High Sierra. If you are interested in researching in that field please let us know how that goes!

**Comment by zysuper** [comment]
just wait NVIDIA release mojave web driver

**Comment by andyy24** [comment]
> > Hi, guys!
> > So does the dGPU implement the NVIDIA Optimus technology? That is, is there any hope for driving the NVIDIA card?🤔️
> > In Chinese:
> > 所以说，这个英伟达显卡是Optimus技术吗？也就是说显卡是不是无望了。如果不是Optimus技术，那么用High Sierra还是可以的，因为有web driver
> 
> I am pretty sure it is Optimus. If not, iGPU will be completely disabled (which you can do in BIOS) so it is not completely hopeless. However I have not test that option on High Sierra. If you are interested in researching in that field please let us know how that goes!

最新的BIOS(1.17)可以完全屏蔽IGPU,所以很难说是不是用了Optimus技术.

The latest BIOS (1.17) can  completely disabled IGPU, so it's hard to say if Optimus technology is used.

**Comment by wu-hongjun** [comment]
It is when you have both of them on, but maybe not when only dGPU.

**Comment by lingster** [comment]
Hi, my understanding is that nvidia will not be supported as apple don't make machines with nvidia cards and hence there are no nvidia macos drivers. 




On Thu, Jan 10, 2019 at 3:01 AM +0000, "Hongjun Wu" <notifications@github.com> wrote:












It is when you have both of them on, but maybe not when only dGPU.

**Comment by wu-hongjun** [comment]
yep no nvidia webdriver out yet.

**Comment by zysuper** [comment]
High Sierra can install Nvidia web driver, but it can't work when I tested.
Whether or not to disable IGPU in bios.

**Comment by wellrex** [comment]
> So I worked based on your work, and came up with an own solution of mine.
> It is currently posted at https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/releases/tag/v10.14.0.1
> 
> First, I'd like to thank you for your work, as it contributed hugely to my project.
> And there are several things I discovered that might be useful for people.
> 
> 1. I tried to make SMBIOS with MacBook 15,1 work, but it suffers from poor compatibilities, so you are correct on setting SMBIOS to 15,2.
> 2. While using the SSDT patches, there are two SSDTs that doesn't work on my machine. One is the SSDT_NVMe-Pcc.aml, which leads to a kernel panic. Another is SSDT-DDGPU.aml, which leads to a reboot after ten seconds the system is logged in. I am curious how you bypass these problems.
> 3. AppleALC isn't working properly on my machine. It is not a big deal since I solved it using VoodooHDA.kext, but I am really interested to know how you attempted to solve AppleALC.kext.
> 4. In your readme.MD you said that the reason for not having NVIDIA card working is because there isn't appropriate web driver, but I think since the dGPU implements the NVIDIA Optimus technology which is not supported by macOS, dGPU is unlikely to work no matter what.
> 
> Again, thanks and I hope these also help other people!
我直接用zysuper的dsdt会卡bios，单用ssdt功能都正常，提取了自己的dsdt，通过对比差异依样画葫芦做了修改，现在功能完全正常了。我想你的ssdt和AppleALC无法工作，大概是dsdt造成的，配置有一点不一样就要编译自己的。再次感谢@zysuper让我吃上了黑果。

**Comment by sudamu** [comment]
Hi, @zysuper , 

I want to thank you for your works on which I relied on heavily while installing the Mac 10.14.2 on my Thinkpad x1 extreme. The OS run basically fine but with some glitches and freezes from time to time. maybe I ask what is the second HD and extra memory you install the machine? I think it might be due to different hardware issue....so want to find out..

thanks a lot!

**Comment by zysuper** [comment]
sumsang 960 evo and Kingston impact ddr 2666 16g. ps: never use sumsang pm981 to install macos.

**Comment by sudamu** [comment]
@zysuper thanks a lot. Samsung 960 eve now is hard to get, guess I would get 1 500G SM 970 evo instead.  and Btw, do you have issue with AppleALC.kext? I tried the method you mentioned and it seems the kext would make the system unstable (sometimes can't boot in). Now I had removed it and so far the system work perfectly with BCM94352z. will try VoodooHDA later perhaps.

**Comment by gfoury** [comment]
I have "Samsung SSD 970 EVO 1TB" which seems to work fine. I got a good deal on memory at purchase, and have the factory 2*16GB 2667MHz Samsung.

**Comment by rsdev69** [comment]
Hi, can you tell me how you did screen resolution 1680x945. I only have the max 1440x810.

**Comment by wdde** [comment]
Hello everyone,
 I met a problem, I have two NVME ssd, one EVO 970 500g (hackintosh), another is the "Union Memory" lens30512gmsp34meat3ta (windows10), I have removed /EFI/CLOVER/ACPI/patched/SSDT_NVMe-Pcc.aml located on evo 970 EFI partition, However, this LENSE ssd is still not visible in the mac, is the mac not compatible with this ssd, or other reasons? Any suggestions? In addition, I installed tuxera NTFS, which makes the ntfs usb disk read and write normally. If the mac recognizes LENSE ssd, it should be able to read and write it. Is this true?
<img width="468" alt="屏幕快照 2019-04-03 下午7 52 54" src="https://user-images.githubusercontent.com/10916526/55477480-c0e0ba80-564b-11e9-970c-3f7e66beef35.png">
<img width="556" alt="屏幕快照 2019-04-03 下午7 51 10" src="https://user-images.githubusercontent.com/10916526/55477496-c807c880-564b-11e9-9686-a056e3c1538f.png">

**Comment by zysuper** [comment]
My machine has 4K screen. 1080p screen is hard to have a good hidpi experience.@rsdev69

**Comment by wdde** [comment]
Hi，zysuper,我前面的问题能给点建议吗？是不是这个亿联ssd就是不兼容macos所以无法识别？还是需要打什么补丁？我计划换掉这个垃圾ssd，不过换成什么还没定，可选的有东芝xg3/wd SN750，因为是win10用的，所以我已经装好的macOS不动（在970evo里），所以我有些疑惑，是不是简单的替换掉win10的ssd就可以？

**Comment by wdde** [comment]
> Hi，zysuper,我前面的问题能给点建议吗？是不是这个亿联ssd就是不兼容macos所以无法识别？还是需要打什么补丁？我计划换掉这个垃圾ssd，不过换成什么还没定，可选的有东芝xg3/wd SN750，因为是win10用的，所以我已经装好的macOS不动（在970evo里），所以我有些疑惑，是不是简单的替换掉win10的ssd就可以？

edit:
买了一根了970 evo 1TB替换了原来的亿联ssd，macos能正常识别这个ssd,并且可以读写了。
