### ISSUE TITLE
USB无线网卡的问题请教一下

### ISSUE THREAD

**Issue by andyy24** [zysuper/Thinkpad-X1-extreme-EFI#4]
ASUS USB AC53 nano 这个USB网卡的信息比较少，我看了亚马逊上的评价比较两极分化，1星和5星的都很多。请问您使用的时候5G信号网速快吗，会不会影响休眠唤醒(论坛上好多usb网卡有唤醒需要拔下重连的毛病)，另外发热量会不会很大，毕竟这么小的ac网卡好像就只有这个。
比较纠结到底是换内置网卡还是用外置的。如果看到的话麻烦解答一下。

**Comment by zysuper** [comment]
1.速度没问题。
2.休眠，唤醒很完美。
3.能内置还是内置。我是完美主义者，没有蓝牙，宁缺毋滥。

**Comment by andyy24** [comment]
如果稳定性和发热量可以接受的话, 我倒是比较偏向于AC53 nano 
因为原装的9560ac确实很不错, 在windows下性能表现非常完美
另外您是怎么屏蔽蓝牙的,通过dsdt吗?

**Comment by zysuper** [comment]
1.如果你使用的是最新版本的usbinjectall.kext直接在clover启动参数加-uia_exclude=HS14
2.或者直接使用fb-patcher，删除usb的HS14，倒出UsbPots.kext

**Comment by andyy24** [comment]
我看到您在config.plist加了-uia_exclude=HS14，谢谢
