### ISSUE TITLE
Failure to start normally after shutdown

### ISSUE THREAD

**Issue by darkal** [zysuper/Thinkpad-X1-extreme-EFI#6]
您好，请问有没有遇到过，长时间关机再次开机的时候一直无法启动，进度条刚出现就自动重启了，需要切换至-v模式才能引导成功

Hello, have you ever met the problem that you can't start again when you shut down for a long time? The progress bar will restart automatically as soon as it appears. Need to switch to - V mode to boot successfully.

**Comment by darkal** [comment]
Anonymous UUID:       B5C01271-AE1B-268D-40F3-5A9427744209

Mon Dec  3 09:34:14 2018

*** Panic Report ***
panic(cpu 4 caller 0xffffff8003cd84dd): Kernel trap at 0xffffff80042067a0, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0xffffff8004765604, CR3: 0x000000000b579000, CR4: 0x00000000003626e0
RAX: 0x0000000000000000, RBX: 0x000000000000b329, RCX: 0x0000000000000000, RDX: 0xffffff80280a8b40
RSP: 0xffffff81e6993b10, RBP: 0xffffff81e6993b10, RSI: 0xffffff7f8441015e, RDI: 0xffffff8004765604
R8:  0xffffff80283680e8, R9:  0x0000000001000007, R10: 0x0000000000000001, R11: 0x0000000000000000
R12: 0x000000000010cbd8, R13: 0xffffff81e67eb000, R14: 0xffffff80283f4bc8, R15: 0xffffff7f8441015e
RFL: 0x0000000000010246, RIP: 0xffffff80042067a0, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0xffffff8004765604, Error code: 0x0000000000000000, Fault CPU: 0x4, PL: 0, VF: 2

Backtrace (CPU 4), Frame : Return Address
0xffffff81e69935e0 : 0xffffff8003baca9d 
0xffffff81e6993630 : 0xffffff8003ce6893 
0xffffff81e6993670 : 0xffffff8003cd82ba 
0xffffff81e69936e0 : 0xffffff8003b59ca0 
0xffffff81e6993700 : 0xffffff8003bac4b7 
0xffffff81e6993820 : 0xffffff8003bac303 
0xffffff81e6993890 : 0xffffff8003cd84dd 
0xffffff81e6993a00 : 0xffffff8003b59ca0 
0xffffff81e6993a20 : 0xffffff80042067a0 
0xffffff81e6993b10 : 0xffffff8004206307 
0xffffff81e6993b50 : 0xffffff8004206b33 
0xffffff81e6993bc0 : 0xffffff8004204bd5 
0xffffff81e6993c50 : 0xffffff8004205579 
0xffffff81e6993cc0 : 0xffffff80041d2be1 
0xffffff81e6993da0 : 0xffffff80041d0aac 
0xffffff81e6993e10 : 0xffffff80041de658 
0xffffff81e6993e60 : 0xffffff800424dc0b 
0xffffff81e6993e80 : 0xffffff800422b8e1 
0xffffff81e6993f00 : 0xffffff800422b4c7 
0xffffff81e6993f50 : 0xffffff800422cf96 
0xffffff81e6993fa0 : 0xffffff8003b590ce 

BSD process name corresponding to current thread: Unknown
Boot args: igfxcflbklt=none -lilubetaall -cdfon uia_exclude=HS14,HS05,HS06,USR1,USR2 

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64
Kernel UUID: 5D53F7E4-472A-369D-97D8-4DD877A4BDFF
Kernel slide:     0x0000000003800000
Kernel text base: 0xffffff8003a00000
__HIB  text base: 0xffffff8003900000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)

System uptime in nanoseconds: 1664723589
last loaded kext at 1659546145: com.insanelymac.IntelMausiEthernet	2.4.1d1 (addr 0xffffff7f87906000, size 135168)
loaded kexts:
(none)

EOF

System Profile:
Boot Volume File System Type: apfs
Memory Module: BANK 0/DIMM0, 16 GB, DDR4, 2667 MHz, Micron Technology, 16ATF2G64HZ-2G6E1
USB Device: USB 3.1 Bus
USB Device: USB3.0-CRW
USB Device: Integrated IR Camera
USB Device: Pen and multitouch sensor
USB Device: Vendor-Specific Device
USB Device: Integrated Camera
USB Device: 802.11n NIC
USB Device: USB Optical Mouse
USB Device: USB 3.1 Bus
Thunderbolt Bus: 
Model: MacBookPro15,2, BootROM 220.200.252.0.0, 6 processors, Intel Core i7, 2.21 GHz, 16 GB, SMC 2.44f1
Graphics: Intel UHD Graphics 630, Intel UHD Graphics 630, Built-In
Network Service: 802.11n NIC, Ethernet, en1

**Comment by zysuper** [comment]
From 10.14.4, after update clover, this problem never happened again.

**Comment by darkal** [comment]
yeah, after update clover , this problem never happened again
