### ISSUE TITLE
请教一下, 现在我想用nvem0了,请问如何取消屏蔽

### ISSUE THREAD

**Issue by andyy24** [zysuper/Thinkpad-X1-extreme-EFI#9]
请教一下, 现在我想用nvem0了,请问如何取消屏蔽

Now I want to use nvem0, how to re-enable

**Comment by darkal** [comment]
Remove /EFI/CLOVER/ACPI/patched/SSDT_NVMe-Pcc.aml

**Comment by andyy24** [comment]
Thank you very much

**Comment by wdde** [comment]
Hi zysuper, I am using your efi file and running the hackintosh, thanks for your work, I found the cursor would move to another location when I typing words. I also have the similar question with andyy24,my first nvme0 hold the win10 and the second nvme1 hold the macOS mojove, I need to access the windows partition by installed tuxera., how can I get it done?

**Comment by zysuper** [comment]
https://github.com/zysuper/Thinkpad-X1-extreme-EFI/issues/9#issuecomment-452935110

**Comment by wdde** [comment]
Thanks, I'll try it.
